### ISSUE TITLE
Unable to add a draw/upload signature

### ISSUE THREAD

**Issue by Kathak09** [damat/SimpleSignature#2]
I am trying to insert a signature using the draw feature, but I am not being provided this option.

**Comment by damat** [comment]
Here's how it looks on my side: https://i.imgur.com/YQ2lSI6.gif 
Does it work in the same way for you?

**Comment by Kathak09** [comment]
For some reason it won't allow me to open the link you send.

**Comment by damat** [comment]
How about this?

![YQ2lSI6](https://user-images.githubusercontent.com/914556/81717868-c3832580-9483-11ea-940b-d4100c3cda74.gif)

**Comment by Kathak09** [comment]
For some reason, I am unable to do that.

**Comment by damat** [comment]
Sorry for the delayed answer. There's not much we can try to do about it, since everything is handled by Google Platform basically. The only possible thing here is trying to uninstall the add-on and install it back. Could you please try that?

**Comment by damat** [comment]
Closed with no feedback from the customer
